# Generated by Django 3.2.4 on 2021-06-27 21:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefered_contact_method', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email')], default='email', max_length=5)),
                ('company_name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, "Please enter your company's name.")])),
                ('first_name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Please enter your first name name.')])),
                ('last_name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Please enter your last name name.')])),
                ('email', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Please enter your E-mail address.')])),
                ('phone_number', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(10, 'Please enter your phone number.')])),
                ('comments', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(0, 'Let us know what service you are interested in.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
