# Generated by Django 3.2.4 on 2021-09-27 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='prefered_contact_method',
            new_name='preferred_contact_method',
        ),
    ]
