# Generated by Django 3.2.4 on 2022-03-12 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_prefered_contact_method_contact_preferred_contact_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasBeenContacted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_been_contacted', models.BooleanField(default=False)),
                ('last_contact', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.contact')),
            ],
        ),
    ]
