# Generated by Django 3.2.4 on 2022-03-12 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_hasbeencontacted'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='has_been_contacted',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='HasBeenContacted',
        ),
    ]
