# Generated by Django 3.2.4 on 2022-03-14 23:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_todo', models.CharField(help_text='Enter the task you want to accomplish.', max_length=255, validators=[django.core.validators.MinLengthValidator(3, 'Come on at least use a acronym!')])),
                ('task_dependencies', models.CharField(help_text='Enter what dependencies if any this task has.', max_length=255, validators=[django.core.validators.MinLengthValidator(3, 'Come on at least use a acronym!')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
