# Generated by Django 3.2.4 on 2021-07-07 02:05

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verify',
            name='customer_number',
            field=models.CharField(default=django.utils.timezone.now, help_text='Please scan the tray id.', max_length=100, validators=[django.core.validators.MinLengthValidator(10, 'Please scan the tray id.')]),
            preserve_default=False,
        ),
    ]
